/**
 * Code Generation Script
 *
 * Reads from the canonical sources of truth (node-registry, integrations, constants)
 * and generates derived code for the CLI (Rust) so that adding a new integration
 * or node type only requires updating the TypeScript definitions.
 *
 * Usage:
 *   pnpm codegen
 *
 * What it generates:
 *   - cli/src/generated.rs  — node types, config keys, integration metadata
 */

import { NODE_CONFIGS, NODE_TYPES } from '../lib/node-registry';
import { AI_MODELS } from '../lib/constants';
import { getAllIntegrations } from '../lib/integrations/registry';
import { INTEGRATION_CONFIG_KEYS } from '../lib/integrations/types';
import * as fs from 'fs';
import * as path from 'path';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function escapeRustStr(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

// ---------------------------------------------------------------------------
// Gather data
// ---------------------------------------------------------------------------

const nodeTypes = NODE_TYPES as string[];

const configKeyMap: Record<string, string | null> = {};
for (const nt of nodeTypes) {
  const cfg = NODE_CONFIGS[nt as keyof typeof NODE_CONFIGS];
  configKeyMap[nt] = cfg.configKey ?? null;
}

const allConfigKeys = Object.values(configKeyMap).filter(
  (k): k is string => k !== null
);

const integrations = getAllIntegrations();
const integrationIds = Object.keys(INTEGRATION_CONFIG_KEYS);

interface IntegrationData {
  id: string;
  name: string;
  description: string;
  category: string;
  configFields: string[];
  authType: string;
  envVar: string;
}

const integrationData: IntegrationData[] = integrations.map((i) => {
  const configFields = i.defaultConfig
    ? Object.keys(i.defaultConfig as Record<string, unknown>)
    : [];

  let envVarStr = '(none)';
  if (i.auth.type === 'api_key' && i.auth.envVar) {
    envVarStr = i.auth.envVar;
  } else if (i.auth.type === 'oauth') {
    envVarStr = i.auth.requiresUserAuth ? '(OAuth - user auth)' : '(OAuth)';
  }

  return {
    id: i.id,
    name: i.name,
    description: i.description,
    category: i.category,
    configFields,
    authType: i.auth.type,
    envVar: envVarStr,
  };
});

const aiModels = AI_MODELS as { value: string; label: string }[];

// ---------------------------------------------------------------------------
// Generate Rust source
// ---------------------------------------------------------------------------

function generateRust(): string {
  const lines: string[] = [];

  lines.push('// ==========================================================================');
  lines.push('// AUTO-GENERATED FILE — DO NOT EDIT');
  lines.push('//');
  lines.push('// Generated by: pnpm codegen  (scripts/codegen.ts)');
  lines.push('// Source of truth: lib/node-registry.ts, lib/integrations/, lib/constants.ts');
  lines.push('// ==========================================================================');
  lines.push('');
  lines.push('#![allow(dead_code)]');
  lines.push('');

  // --- Valid node types ---
  lines.push('/// All valid workflow node types.');
  lines.push(`pub const VALID_NODE_TYPES: &[&str] = &[${nodeTypes.map((t) => `"${t}"`).join(', ')}];`);
  lines.push('');

  // --- Config key for type ---
  lines.push('/// Return the config-key name for a given node type (e.g. "email" → "emailConfig").');
  lines.push('pub fn config_key_for_type(node_type: &str) -> Option<&\'static str> {');
  lines.push('    match node_type {');
  for (const nt of nodeTypes) {
    const ck = configKeyMap[nt];
    if (ck) {
      lines.push(`        "${nt}" => Some("${ck}"),`);
    }
  }
  lines.push('        _ => None,');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  // --- All config keys ---
  lines.push('/// Every config-key that may appear on a workflow node.');
  lines.push(`pub const ALL_CONFIG_KEYS: &[&str] = &[${allConfigKeys.map((k) => `"${k}"`).join(', ')}];`);
  lines.push('');

  // --- Integration metadata struct ---
  lines.push('pub struct IntegrationMeta {');
  lines.push('    pub id: &\'static str,');
  lines.push('    pub name: &\'static str,');
  lines.push('    pub description: &\'static str,');
  lines.push('    pub category: &\'static str,');
  lines.push('    pub config_fields: &\'static [&\'static str],');
  lines.push('    pub env_var: &\'static str,');
  lines.push('}');
  lines.push('');

  // --- Integration constants ---
  lines.push('/// All registered integrations.');
  lines.push(`pub const INTEGRATIONS: &[IntegrationMeta] = &[`);
  for (const i of integrationData) {
    lines.push('    IntegrationMeta {');
    lines.push(`        id: "${escapeRustStr(i.id)}",`);
    lines.push(`        name: "${escapeRustStr(i.name)}",`);
    lines.push(`        description: "${escapeRustStr(i.description)}",`);
    lines.push(`        category: "${escapeRustStr(i.category)}",`);
    lines.push(`        config_fields: &[${i.configFields.map((f) => `"${escapeRustStr(f)}"`).join(', ')}],`);
    lines.push(`        env_var: "${escapeRustStr(i.envVar)}",`);
    lines.push('    },');
  }
  lines.push('];');
  lines.push('');

  // --- Integration IDs ---
  lines.push('/// All integration IDs.');
  lines.push(`pub const INTEGRATION_IDS: &[&str] = &[${integrationIds.map((id) => `"${id}"`).join(', ')}];`);
  lines.push('');

  // --- Integration lookup ---
  lines.push('/// Look up integration metadata by ID.');
  lines.push('pub fn integration_info(id: &str) -> Option<&\'static IntegrationMeta> {');
  lines.push('    INTEGRATIONS.iter().find(|i| i.id == id)');
  lines.push('}');
  lines.push('');

  // --- AI models ---
  lines.push('pub struct AiModel {');
  lines.push('    pub value: &\'static str,');
  lines.push('    pub label: &\'static str,');
  lines.push('}');
  lines.push('');
  lines.push('/// All available AI models.');
  lines.push('pub const AI_MODELS: &[AiModel] = &[');
  for (const m of aiModels) {
    lines.push(`    AiModel { value: "${escapeRustStr(m.value)}", label: "${escapeRustStr(m.label)}" },`);
  }
  lines.push('];');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Write files
// ---------------------------------------------------------------------------

const rootDir = path.resolve(__dirname, '..');
const cliGeneratedPath = path.join(rootDir, 'cli', 'src', 'generated.rs');

const rustSource = generateRust();
fs.writeFileSync(cliGeneratedPath, rustSource, 'utf-8');

console.log(`Generated ${cliGeneratedPath}`);
console.log(`  - ${nodeTypes.length} node types`);
console.log(`  - ${integrationData.length} integrations`);
console.log(`  - ${aiModels.length} AI models`);
console.log(`  - ${allConfigKeys.length} config keys`);
