// ==========================================================================
// AUTO-GENERATED FILE — DO NOT EDIT
//
// Generated by: pnpm codegen  (scripts/codegen.ts)
// Source of truth: lib/node-registry.ts, lib/integrations/, lib/constants.ts
// ==========================================================================

#![allow(dead_code)]

/// All valid workflow node types.
pub const VALID_NODE_TYPES: &[&str] = &["entry", "ai", "scheduler", "review", "email", "slack", "sms", "telegram", "condition", "youtube"];

/// Return the config-key name for a given node type (e.g. "email" → "emailConfig").
pub fn config_key_for_type(node_type: &str) -> Option<&'static str> {
    match node_type {
        "ai" => Some("aiConfig"),
        "scheduler" => Some("schedulerConfig"),
        "review" => Some("reviewConfig"),
        "email" => Some("emailConfig"),
        "slack" => Some("slackConfig"),
        "sms" => Some("smsConfig"),
        "telegram" => Some("telegramConfig"),
        "condition" => Some("conditionConfig"),
        "youtube" => Some("youtubeConfig"),
        _ => None,
    }
}

/// Every config-key that may appear on a workflow node.
pub const ALL_CONFIG_KEYS: &[&str] = &["aiConfig", "schedulerConfig", "reviewConfig", "emailConfig", "slackConfig", "smsConfig", "telegramConfig", "conditionConfig", "youtubeConfig"];

pub struct IntegrationMeta {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub category: &'static str,
    pub config_fields: &'static [&'static str],
    pub env_var: &'static str,
}

/// All registered integrations.
pub const INTEGRATIONS: &[IntegrationMeta] = &[
    IntegrationMeta {
        id: "email",
        name: "Email",
        description: "Send emails via Resend",
        category: "communication",
        config_fields: &["to", "subject", "message", "from"],
        env_var: "RESEND_API_KEY",
    },
    IntegrationMeta {
        id: "slack",
        name: "Slack",
        description: "Send messages to Slack channels",
        category: "communication",
        config_fields: &["botId", "channel", "message"],
        env_var: "(OAuth - user auth)",
    },
    IntegrationMeta {
        id: "sms",
        name: "SMS",
        description: "Send text messages via Twilio",
        category: "communication",
        config_fields: &["to", "message", "twilioAccountSid", "twilioAuthToken", "twilioPhoneNumber"],
        env_var: "TWILIO_ACCOUNT_SID",
    },
    IntegrationMeta {
        id: "telegram",
        name: "Telegram",
        description: "Send messages to Telegram chats",
        category: "communication",
        config_fields: &["chatId", "message", "botToken"],
        env_var: "TELEGRAM_BOT_TOKEN",
    },
    IntegrationMeta {
        id: "condition",
        name: "Condition",
        description: "Branch workflow based on a condition",
        category: "utility",
        config_fields: &["leftValue", "operator", "rightValue"],
        env_var: "(none)",
    },
    IntegrationMeta {
        id: "youtube",
        name: "YouTube",
        description: "Fetch video data or post comments via YouTube API",
        category: "data",
        config_fields: &["mode", "videoUrl", "commentText"],
        env_var: "(OAuth - user auth)",
    },
    IntegrationMeta {
        id: "discord",
        name: "Discord",
        description: "Send messages to Discord channels via webhook",
        category: "communication",
        config_fields: &["webhookUrl", "message", "username"],
        env_var: "(none)",
    },
    IntegrationMeta {
        id: "http_request",
        name: "HTTP Request",
        description: "Make HTTP requests to any API endpoint",
        category: "utility",
        config_fields: &["url", "method", "headers", "body", "authType", "authValue"],
        env_var: "(none)",
    },
    IntegrationMeta {
        id: "google_sheets",
        name: "Google Sheets",
        description: "Read and write data in Google Sheets",
        category: "data",
        config_fields: &["mode", "spreadsheetId", "range", "values"],
        env_var: "(OAuth - user auth)",
    },
    IntegrationMeta {
        id: "github",
        name: "GitHub",
        description: "Create issues, comments, and manage GitHub repositories",
        category: "data",
        config_fields: &["action", "repo", "title", "body", "token"],
        env_var: "GITHUB_TOKEN",
    },
    IntegrationMeta {
        id: "notion",
        name: "Notion",
        description: "Create pages, query databases, and manage Notion content",
        category: "data",
        config_fields: &["action", "databaseId", "title", "content", "apiKey"],
        env_var: "NOTION_API_KEY",
    },
    IntegrationMeta {
        id: "airtable",
        name: "Airtable",
        description: "Read and write records in Airtable bases",
        category: "data",
        config_fields: &["action", "baseId", "tableId", "recordId", "fields", "apiKey"],
        env_var: "AIRTABLE_API_KEY",
    },
    IntegrationMeta {
        id: "whatsapp",
        name: "WhatsApp",
        description: "Send WhatsApp messages via Twilio",
        category: "communication",
        config_fields: &["to", "message", "twilioAccountSid", "twilioAuthToken", "twilioPhoneNumber"],
        env_var: "TWILIO_ACCOUNT_SID",
    },
    IntegrationMeta {
        id: "jira",
        name: "Jira",
        description: "Create and manage Jira issues",
        category: "data",
        config_fields: &["action", "domain", "email", "apiToken", "projectKey", "issueKey", "summary", "description", "issueType", "priority", "transitionId", "comment", "jql"],
        env_var: "JIRA_API_TOKEN",
    },
    IntegrationMeta {
        id: "hubspot",
        name: "HubSpot",
        description: "Manage contacts and deals in HubSpot CRM",
        category: "data",
        config_fields: &["action", "accessToken", "email", "firstName", "lastName", "phone", "company", "contactId", "dealName", "dealStage", "amount", "pipeline", "dealId", "searchQuery"],
        env_var: "HUBSPOT_ACCESS_TOKEN",
    },
    IntegrationMeta {
        id: "webhook",
        name: "Webhook",
        description: "Send data to any URL via outgoing webhook",
        category: "utility",
        config_fields: &["url", "method", "headers", "bodyTemplate", "authType", "authValue", "retryOnFailure", "maxRetries"],
        env_var: "(none)",
    },
];

/// All integration IDs.
pub const INTEGRATION_IDS: &[&str] = &["email", "slack", "sms", "telegram", "condition", "youtube", "discord", "http_request", "google_sheets", "github", "notion", "airtable", "whatsapp", "jira", "hubspot", "webhook"];

/// Look up integration metadata by ID.
pub fn integration_info(id: &str) -> Option<&'static IntegrationMeta> {
    INTEGRATIONS.iter().find(|i| i.id == id)
}

pub struct AiModel {
    pub value: &'static str,
    pub label: &'static str,
}

/// All available AI models.
pub const AI_MODELS: &[AiModel] = &[
    AiModel { value: "openai/gpt-4o", label: "GPT-4o" },
    AiModel { value: "openai/gpt-4o-mini", label: "GPT-4o Mini" },
    AiModel { value: "openai/gpt-4-turbo", label: "GPT-4 Turbo" },
    AiModel { value: "openai/gpt-3.5-turbo", label: "GPT-3.5 Turbo" },
    AiModel { value: "anthropic/claude-3.5-sonnet", label: "Claude 3.5 Sonnet" },
    AiModel { value: "anthropic/claude-3-haiku", label: "Claude 3 Haiku" },
    AiModel { value: "google/gemini-2.0-flash-001", label: "Gemini 2.0 Flash" },
    AiModel { value: "google/gemini-pro", label: "Gemini Pro" },
    AiModel { value: "meta-llama/llama-3.1-405b-instruct", label: "Llama 3.1 405B" },
    AiModel { value: "meta-llama/llama-3.1-70b-instruct", label: "Llama 3.1 70B" },
    AiModel { value: "meta-llama/llama-3.1-8b-instruct", label: "Llama 3.1 8B" },
];
